settings:
  # Время по умолчанию в секундах, если не указано в команде
  default-time: 120
  # С какой секунды начинать отсчет в чате и на экране
  countdown-start: 30

bossbar:
  # Заголовок боссбара
  title: "&4&lВНИМАНИЕ! &fПерезагрузка сервера через &6&l{time} &fсек."
  color: "RED"
  style: "SOLID"

messages:
  no-permission: "&cУ вас нет прав на использование этой команды!"
  already-started: "&cПерезагрузка уже запущена!"
  invalid-number: "&cНеверное число! Будет использовано стандартное время."
  reload-success: "&aКонфигурация TwRestart успешно перезагружена!"
  reload-usage: "&cИспользуйте: /twrestart reload"

  restart-cancelled: "&aПерезагрузка была отменена."
  not-running: "&cТаймер перезагрузки в данный момент не запущен."

  # Крупный заголовок
  title-header: "&4&lВНИМАНИЕ!"

  # Нижняя строка Title (Отсчет: "Перезагрузка сервера через 300 сек.")
  title-footer: "&fПерезагрузка сервера через &6&l{time} &fсек."

  # Сообщение в чате при финальном отсчете
  chat-countdown: "&c&lАвто рестарт &7>> &fПерезагрузка сервера через &6&l{time} &fсек."

# Список команд, которые выполнятся в консоли, когда время выйдет
commands-on-finish:
  - "restart"